name: CI

on:
  pull_request:
    branches:
      - 'main'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project sources
        uses: actions/checkout@v3
      - name: setup jdk 19
        uses: actions/setup-java@v3
        with:
          java-version: '19.0.2'
          distribution: 'temurin'
      - name: run tests
        run: ./gradlew test

